forms refresh saving product and commitment
selsa-inube/iprocess pull request #21
Opened 2024-07-31 20:27 UTC by ANGIECATHERINEP

In this branch, the forms of savings were created:
RefreshSavingProduct
RefreshSavingCommitment

In the path src\pages\startProcess\tabs\scheduled\components\StartProcess\index.tsx one of the forms was added temporarily so that it can be displayed in the modal when clicking on the start processes icon in the scheduled table (in start processes)

2024-08-01 16:14 UTC, LinconOssa approved these changes
meets requirements

2024-08-13 15:45 UTC, Dlfp requested changes

2024-08-13 15:45 UTC, Dlfp commented on src/mocks/domains/typeRefresh.mocks.ts
> +const typeRefreshData=[
Este archivo se puede quitar el proyecto dado que ya está usando el servicio de proceso

2024-08-13 19:17 UTC, Dlfp approved these changes

2024-08-13 19:17 UTC, merged