Create the tab options in iniciar procesos
selsa-inube/iprocess pull request #5
Opened 2024-06-24 14:48 UTC by ANGIECATHERINEP

Create the tab options in iniciar procesos

2024-06-25 02:07 UTC, LinconOssa reviewed
In the figure it says that the text to start processes is processes to start:
![image](https://github.com/selsa-inube/iprocess/assets/103295353/0210b892-4e43-44ed-b698-b889b03b0e57)

2024-06-25 13:57 UTC, LinconOssa approved these changes
Meets requirements

2024-06-25 14:29 UTC, Dlfp requested changes
Por favor quitar el breadcrumbs porque no tiene sentido dejar la palabra Home.

2024-06-25 14:29 UTC, Dlfp commented on src/pages/startProcess/interface.tsx
> +      padding={smallScreen ? "s300" : "s400 s800"}
Estas segura si el sistema de diseño recibe el dato s300? porque debería enviarlo en pixeles

2024-06-25 14:29 UTC, Dlfp commented on src/pages/startProcess/styles.ts
> +const StyledMessageContainer = styled.div`
Esta constante no se está usando .. para qué fue creado? si no es requerido debes eliminarlo

2024-06-25 15:32 UTC, ANGIECATHERINEP commented on src/pages/startProcess/interface.tsx
> +      padding={smallScreen ? "s300" : "s400 s800"}
Resuelto

2024-06-28 12:52 UTC, carin91 approved these changes

2024-06-28 12:52 UTC, merged