check portal and operator data
selsa-inube/iprocess pull request #58
Opened 2024-10-12 00:41 UTC by ANGIECATHERINEP

check portal and operator data.
 
In this repository the tasks of the jira cards were performed:
-prcss85
-prcss86

2024-10-17 17:26 UTC, LinconOssa approved these changes
Cumple con requerimientos

2024-10-18 01:04 UTC, cmarin001 commented on src/components/layout/AppPage/AppPage.stories.tsx
> +    businessUnit:{
Check that setup since it shouldn't be there, this is IProcess not Linpar, and that data can't be hardcoded like that

2024-10-18 01:08 UTC, cmarin001 commented on src/utils/encrypt.ts
> +  "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
I think I would be better if this secretKey comes from an environment variable

2024-10-18 01:08 UTC, cmarin001 requested changes
Please check the comments

2024-10-21 13:43 UTC, cmarin001 approved these changes

2024-10-21 13:43 UTC, merged