Remove temp business unit
selsa-inube/iprocess pull request #68
Opened 2024-10-29 13:16 UTC by ANGIECATHERINEP

Remove temp business unit

2024-10-29 23:48 UTC, cmarin001 commented on src/forms/card/RefreshCardCreditProduct/index.tsx
>  import * as Yup from "yup";
same on here

2024-10-29 23:48 UTC, cmarin001 commented on src/forms/card/RefreshSavingProductCard/index.tsx
>  import * as Yup from "yup";
same on there

2024-10-29 23:48 UTC, cmarin001 commented on src/forms/credit/RefreshCreditRequest/index.tsx
>  import * as Yup from "yup";
same on there

2024-10-29 23:49 UTC, cmarin001 commented on src/forms/customers/RefreshCustomerAttributes/index.tsx
>  import * as Yup from "yup";
same on there

2024-10-29 23:49 UTC, cmarin001 commented on src/forms/otherDebt/RefreshOtherDebt/index.tsx
>  import * as Yup from "yup";
Please import only the specific modules you need. Using * imports everything from the library, which is inefficient as it loads unnecessary components each time.

2024-10-29 23:49 UTC, cmarin001 commented on src/forms/portfolio/RefreshPortfolioObligation/index.tsx
>  import * as Yup from "yup";
Please import only the specific modules you need. Using * imports everything from the library, which is inefficient as it loads unnecessary components each time.

2024-10-29 23:49 UTC, cmarin001 commented on src/forms/savings/RefreshSavingCommitment/index.tsx
>  import * as Yup from "yup";
Please import only the specific modules you need. Using * imports everything from the library, which is inefficient as it loads unnecessary components each time.

2024-10-29 23:53 UTC, cmarin001 requested changes
please check the comments

2024-11-01 02:37 UTC, cmarin001 commented on src/forms/card/RefreshCard/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly, like `import { string, object } from "yup";`. These are the only elements being used for validation in this component, so this approach keeps the code efficient and focused. Then, defining the validation schema becomes straightforward:
`const validationSchema = object({
  typeRefresh: string().required("Este campo no puede estar vacío"),
  descriptionComplementary: string(),
  plannedExecutionDate: string(),
});
`

2024-11-01 02:38 UTC, cmarin001 commented on src/forms/card/RefreshCardCreditProduct/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:38 UTC, cmarin001 commented on src/forms/card/RefreshSavingProductCard/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:39 UTC, cmarin001 commented on src/forms/credit/RefreshCreditRequest/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:39 UTC, cmarin001 commented on src/forms/customers/RefreshCustomerAttributes/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:39 UTC, cmarin001 commented on src/forms/otherDebt/RefreshOtherDebt/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:39 UTC, cmarin001 commented on src/forms/portfolio/RefreshPortfolioObligation/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:39 UTC, cmarin001 commented on src/forms/savings/RefreshSavingCommitment/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-01 02:39 UTC, cmarin001 commented on src/forms/savings/RefreshSavingProduct/index.tsx
>  import * as Yup from "yup";
That adjustment doesn’t address the issue because it only wraps the entire import under an alias Yup, which still imports everything from yup. Instead, I suggest importing only the required parts directly

2024-11-05 13:30 UTC, ANGIECATHERINEP commented on src/forms/card/RefreshCard/index.tsx
>  import * as Yup from "yup";
I had already made these adjustments :)
![image](https://github.com/user-attachments/assets/be76384d-9de6-442c-af76-d1245c429328)

2024-11-05 13:31 UTC, ANGIECATHERINEP commented on src/forms/card/RefreshCardCreditProduct/index.tsx
>  import * as Yup from "yup";
![image](https://github.com/user-attachments/assets/fbc2a76e-863a-4b9b-9d30-5e2ee31555c0)

2024-11-05 21:31 UTC, cmarin001 approved these changes

2024-11-05 21:31 UTC, merged